/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OMGzombiesSettings.java
 *
 * Created on 12 janv. 2012, 11:42:58
 */
package v1;



import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author yoda
 */
public class SettingsWindow extends javax.swing.JFrame {
	
	/**
	 * generate by eclipse ... needed for JFrame ...
	 */
	private static final long serialVersionUID = -3275653491163613005L;
	private Simulator sim;
	private SimulatorThread simulatorThread;
	

    /** Creates new form OMGzombiesSettings */
    public SettingsWindow(Simulator sim) {
    	this.sim = sim;
    	
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	
    	
        jSliderSpeed = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jFormattedTextFieldNbZombies = new javax.swing.JFormattedTextField(new Float(0.0000));
        jFormattedTextFieldNbVampires = new javax.swing.JFormattedTextField(new Float(0.0000));
        jFormattedTextFieldNbMadZombies = new javax.swing.JFormattedTextField(new Float(0.0000));
        jFormattedTextFieldNbHumans = new javax.swing.JFormattedTextField(new Float(0.0000));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Speed of simulation");

        jSliderSpeed.addChangeListener(new ChangeSlider());
        
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jFormattedTextFieldNbZombies.setText(Double.toString(sim.getZOMBIE_CREATION_PROBABILITY()*100));
        jFormattedTextFieldNbZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNbZombiesActionPerformed(evt);
            }
        });

        jFormattedTextFieldNbVampires.setText(Double.toString(sim.getVAMPIRE_CREATION_PROBABILITY()*100));
        jFormattedTextFieldNbVampires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNbVampiresActionPerformed(evt);
            }
        });

        jFormattedTextFieldNbMadZombies.setText(Double.toString(sim.getMADZOMBIE_CREATION_PROBABILITY()*100));
        jFormattedTextFieldNbMadZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNbMadZombiesActionPerformed(evt);
            }
        });

        jFormattedTextFieldNbHumans.setText(Double.toString(sim.getHUMAN_CREATION_PROBABILITY()*100));
        jFormattedTextFieldNbHumans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNbHumansActionPerformed(evt);
            }
        });

        jLabel2.setText("Humans");

        jLabel3.setText("Zombies");

        jLabel4.setText("MadZombies");

        jLabel5.setText("NbVampires");

        jLabel6.setFont(new java.awt.Font("Domestic Manners", 1, 24)); // NOI18N
        jLabel6.setText("Settings");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Caracters creation probabilities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFormattedTextFieldNbHumans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldNbZombies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldNbMadZombies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldNbVampires, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButtonReset)))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldNbHumans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jFormattedTextFieldNbZombies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldNbMadZombies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldNbVampires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReset)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>

    
    
   
private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {
	double proba;
	try {
        proba = Double.parseDouble(jFormattedTextFieldNbZombies.getText());

    } catch (NumberFormatException e) {

        proba = 0;
    }
	sim.setZOMBIE_CREATION_PROBABILITY(proba/100);
	
	try {
        proba = Double.parseDouble(jFormattedTextFieldNbVampires.getText());

    } catch (NumberFormatException e) {

        proba = 0;
    }
	sim.setVAMPIRE_CREATION_PROBABILITY(proba/100);
	
	try {
        proba = Double.parseDouble(jFormattedTextFieldNbMadZombies.getText());
        

    } catch (Exception e) {
    	proba = 0;
    }
	sim.setMADZOMBIE_CREATION_PROBABILITY(proba/100);
	
	try {
        proba = Double.parseDouble(jFormattedTextFieldNbHumans.getText());

    } catch (NumberFormatException e) {
    	System.out.println(e);
        proba = 0;
    }
	//System.out.println(Double.parseDouble(jFormattedTextFieldNbHumans.getText()));
	
	sim.setHUMAN_CREATION_PROBABILITY(proba/100);
	
	System.out.println(sim.getHUMAN_CREATION_PROBABILITY());
	
	sim.stopSimulation = true;
	simulatorThread = new SimulatorThread("Simulator", sim);
	sim.stopSimulation = false;
	simulatorThread.start();
	
}

private void jFormattedTextFieldNbZombiesActionPerformed(java.awt.event.ActionEvent evt) {
	
}

private void jFormattedTextFieldNbVampiresActionPerformed(java.awt.event.ActionEvent evt) {
	
}

private void jFormattedTextFieldNbMadZombiesActionPerformed(java.awt.event.ActionEvent evt) {
	
}

private void jFormattedTextFieldNbHumansActionPerformed(java.awt.event.ActionEvent evt) {
	
}

public class ChangeSlider implements ChangeListener{
	@Override
	public void stateChanged(ChangeEvent e) {
		// TODO Auto-generated method stub
		System.out.println("delay: "+(-10 * jSliderSpeed.getValue() + 1000));
		sim.speed = -10 * jSliderSpeed.getValue() + 1000;
		
		
	}
}

    /**
     * @param args the command line arguments
     */
    public void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SettingsWindow(sim).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonReset;
    private javax.swing.JFormattedTextField jFormattedTextFieldNbHumans;
    private javax.swing.JFormattedTextField jFormattedTextFieldNbMadZombies;
    private javax.swing.JFormattedTextField jFormattedTextFieldNbVampires;
    private javax.swing.JFormattedTextField jFormattedTextFieldNbZombies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider jSliderSpeed;
    // End of variables declaration
}
